### ISSUE TITLE
希望能够实时显示当前下载任务进度，网速等情况

### ISSUE THREAD

**Issue by snakexgc** [jw-star/aria2bot#11]
有一个项目大佬可以参考一下，他这个项目编程语言也是python，实现了实时任务进度的显示，理论上原理就是不断查询aria2的状态，然后不断修改机器人返回的信息。

项目地址：https://github.com/666wcy/ARPT-Bot

**Comment by jw-star** [comment]
之前有这个想法，但是机器人api有调用限制，就给停了

**Comment by jw-star** [comment]
https://github.com/jw-star/aria2bot/blob/8a980304b5060fe2323449a49ab940fcf7e5ec68/aria2client.py#L77

**Comment by jw-star** [comment]
@snakexgc 已增加进度显示
