### ISSUE TITLE
文件名中含有符号时可能识别任务失败

### ISSUE THREAD

**Issue by snakexgc** [jw-star/aria2bot#12]
![Screenshot_2023-07-02-11-12-40-299_org telegram messenger web-edit](https://github.com/jw-star/aria2bot/assets/78722169/48d6c67d-a1e8-4806-95be-92527abdd870)
如上图，我直接在机器人这发送链接时，文件名是222~1.mp4，但是识别会直接识别成222，然后导致下载失败，下面是我在aria2直接手动添加，是没有问题的，希望大佬解决一下这个问题！感谢大佬的付出！

**Comment by jw-star** [comment]
好的，刚看到，晚上看下

**Comment by jw-star** [comment]
已修复

**Comment by snakexgc** [comment]
修改后遇到了更严重的bug，

**Comment by jw-star** [comment]
发下日志

**Comment by snakexgc** [comment]
![image](https://github.com/jw-star/aria2bot/assets/78722169/c9aece20-f136-4257-a275-50d78747d4d8)
如上图，
1.中文经过URL编码后，添加任务不会解码成中文，直接在ariaNG添加是会转换成中文的
![image](https://github.com/jw-star/aria2bot/assets/78722169/1870020c-bad6-4478-939c-0f99ba03e9c4)

2.mp4文件尾缀识别错误，后面的参数也被加入了尾缀
![image](https://github.com/jw-star/aria2bot/assets/78722169/eadc9071-c56b-48ca-a90a-b2e3999e31e7)

**Comment by snakexgc** [comment]
关于解码这个，之前的版本也不会解码，但是在aria2中会解码，就是我下载好的文件名是解码后的文件名，机器人反馈的信息任然是没有被解码的信息，所以这个可能不算bug

**Comment by snakexgc** [comment]
> 

但是这次，在aria2中下载的文件的文件名也没有解码，然后尾缀的参数也没有被清理

**Comment by jw-star** [comment]
我最近没在玩aria2，所以很难保证测试  你会编码的话，可以试试

**Comment by snakexgc** [comment]
大佬可以考虑将添加任务的那些代码用aria2p进行替代，aria2p的兼容性很强

下面这是他的示例：

import aria2p
aria2 = aria2p.API(
    aria2p.Client(
        host="http://localhost",
        port=6800,
        secret=""
    )
)
uri = "magnet/http"
download = aria2.add(uri)

aria2p的add有很好的兼容性
![image](https://github.com/jw-star/aria2bot/assets/78722169/c047a0fe-0ecb-4cca-847a-758d17a5d728)

详细信息：https://pypi.org/project/aria2p

我本来想试试看，但是奈何python编程能力不到家，试了半天没成功，大佬有时间的话可以试试

**Comment by snakexgc** [comment]
又试了半天，我按我说的那个方法，修复了这个bug，虽然很蠢吧，但是现在可以用了，我自己开了个仓库，期待大佬修复bug

**Comment by jw-star** [comment]
aria2p 没办法回调似乎，最开始我也用的这个的，后来换了

**Comment by snakexgc** [comment]
> aria2p 没办法回调似乎，最开始我也用的这个的，后来换了

我直接吧处理mp4文件那段用aira2p的add用法替代掉了，就是显得有些丑陋，但是至少现在功能是正常的，只是docker-compose文件变得很丑了
