### ISSUE TITLE
建议重启 下载tg上文件计划 非常需要

### ISSUE THREAD

**Issue by JONREAN2** [jw-star/aria2bot#13]

**Comment by jw-star** [comment]
下载tg文件，现在还没有看过，不知道怎么找tg文件的直链

**Comment by jw-star** [comment]
https://github.com/EverythingSuckz/TG-FileStreamBot/blob/main/WebStreamer/bot/plugins/stream.py

似乎这个可以，我后面看看

**Comment by jw-star** [comment]
最好详细描述下你的问题

**Comment by JONREAN2** [comment]
就是支持下载tg上视频与图片

把tg文件转成直链  然后通过aria2 下载

**Comment by jw-star** [comment]
https://github.com/EverythingSuckz/TG-FileStreamBot/blob/main/WebStreamer/bot/plugins/stream.py

建议先搭建这个机器人，配合使用

**Comment by JONREAN2** [comment]
> https://github.com/EverythingSuckz/TG-FileStreamBot/blob/main/WebStreamer/bot/plugins/stream.py
> 
> 
> 
> 建议先搭建这个机器人，配合使用

有了 就是两个bot转发麻烦
