### ISSUE TITLE
下载完了没法上传啊？

### ISSUE THREAD

**Issue by iwvw** [jw-star/aria2bot#14]
![image](https://github.com/jw-star/aria2bot/assets/81206855/e004eae2-70b8-4887-8984-5c38d0284015)
这是怎么一回事呢？

**Comment by iwvw** [comment]
> ![image](https://user-images.githubusercontent.com/81206855/276129766-e004eae2-70b8-4887-8984-5c38d0284015.png) 这是怎么一回事呢？

![image](https://github.com/jw-star/aria2bot/assets/81206855/06fd8b7d-4b9d-4990-988f-12b52b61342c)

**Comment by jw-star** [comment]
看下自己设置的id对吗

**Comment by SuperrNaruto** [comment]
大佬我也是没上传 转发 id 我填的群组 id：-1002262701613
![IMG_5167](https://github.com/user-attachments/assets/c31996f9-ea04-433f-bfaa-1148f58d06a4)
