### ISSUE TITLE
【请求功能】 自动上传aria2下载的文件至群组

### ISSUE THREAD

**Issue by wanyunr** [jw-star/aria2bot#17]
Docker Aria2能够正常使用，但是aria2bot使用它就会报错，
**日志**
```
aria2_bot  | WebSocket连接成功
aria2_bot  | 2024-04-23 19:21:26 debian-s-1vcpu-1gb-sfo3-01 bot[1] INFO Test_240423_Bot bot启动成功...
aria2_bot  | 2024-04-23 19:23:25 debian-s-1vcpu-1gb-sfo3-01 bot[1] INFO 2024-04-23 19:23:25.219551:⬇️正在下载
aria2_bot  | 2024-04-23 19:23:26 debian-s-1vcpu-1gb-sfo3-01 telethon.client.updates[1] ERROR Unhandled exception on send_welcome
aria2_bot  | Traceback (most recent call last):
aria2_bot  |   File "/root/.local/lib/python3.11/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
aria2_bot  |     await callback(event)
aria2_bot  |   File "/app/app.py", line 81, in send_welcome
aria2_bot  |     await downloading(event)
aria2_bot  |   File "/app/app.py", line 203, in downloading
aria2_bot  |     tasks = await client.tell_active()
aria2_bot  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
aria2_bot  |   File "/app/async_aria2_client.py", line 267, in tell_active
aria2_bot  |     return data['result']
aria2_bot  |            ~~~~^^^^^^^^^^
aria2_bot  | KeyError: 'result'
aria2      | 
aria2      | 04/23 19:24:28 [NOTICE] Serialized session to '/config/aria2.session' successfully.
aria2_bot  | rec message:{"jsonrpc":"2.0","method":"aria2.onDownloadStart","params":[{"gid":"875ebec621f5910b"}]}
aria2_bot  | ===========下载 开始 任务id:875ebec621f5910b
aria2      | 
aria2      | 04/23 19:24:31 [NOTICE] Download complete: /downloads/__down
aria2_bot  | 2024-04-23 19:24:31 debian-s-1vcpu-1gb-sfo3-01 asyncio[1] ERROR Task exception was never retrieved
aria2_bot  | future: <Task finished name='Task-23' coro=<AsyncAria2Client.listen() done, defined at /app/async_aria2_client.py:42> exception=KeyError('result')>
aria2_bot  | Traceback (most recent call last):
aria2_bot  |   File "/app/async_aria2_client.py", line 55, in listen
aria2_bot  |     await self.on_download_start(result)
aria2_bot  |   File "/app/async_aria2_client.py", line 128, in on_download_start
aria2_bot  |     tellStatus = await self.tell_status(gid)
aria2_bot  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
aria2_bot  |   File "/app/async_aria2_client.py", line 110, in tell_status
aria2_bot  |     return data['result']
aria2_bot  |            ~~~~^^^^^^^^^^
aria2_bot  | KeyError: 'result'
aria2      | 04/23 19:24:31 [INFO] .aria2 file does not exist.
aria2      | 04/23 19:24:31 [INFO] General download task, skipped delete .torrent file.
aria2      | 04/23 19:24:31 [INFO] Deleting empty directory ...
aria2      | 
aria2      | 04/23 19:24:32 [NOTICE] Serialized session to '/config/aria2.session' successfully.
```

**docker compose**
```docker compose
version: "3.7"
services:
  aria2bot:
    image: jwstar/aria2bot
    network_mode: host
    container_name: aria2_bot
    restart: always
    volumes:
      - ./db:/app/db
      - /root/docker/aria2-downloads:/downloads
      - /qqqq:/qqqq
    build: .
    environment:
      TZ: Asia/Shanghai
  aria2:
    image: p3terx/aria2-pro
    container_name: aria2
    restart: unless-stopped
    ports:
      - "6800:6800"
      - "6888:6888"
      - "6888:6888/udp"
    environment:
      - PUID=$UID
      - PGID=$GID
      - UMASK_SET=022
      - RPC_SECRET=xxx
      - RPC_PORT=6800
      - LISTEN_PORT=6888
    volumes:
      - /root/docker/aria2-config:/config
      - /root/docker/aria2-downloads:/downloads
      - /qqqq:/qqqq
   ```

**Comment by wanyunr** [comment]
> Docker Aria2能够正常使用，但是aria2bot使用它就会报错， **日志**
> 
> ```
> aria2_bot  | WebSocket连接成功
> aria2_bot  | 2024-04-23 19:21:26 debian-s-1vcpu-1gb-sfo3-01 bot[1] INFO Test_240423_Bot bot启动成功...
> aria2_bot  | 2024-04-23 19:23:25 debian-s-1vcpu-1gb-sfo3-01 bot[1] INFO 2024-04-23 19:23:25.219551:⬇️正在下载
> aria2_bot  | 2024-04-23 19:23:26 debian-s-1vcpu-1gb-sfo3-01 telethon.client.updates[1] ERROR Unhandled exception on send_welcome
> aria2_bot  | Traceback (most recent call last):
> aria2_bot  |   File "/root/.local/lib/python3.11/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
> aria2_bot  |     await callback(event)
> aria2_bot  |   File "/app/app.py", line 81, in send_welcome
> aria2_bot  |     await downloading(event)
> aria2_bot  |   File "/app/app.py", line 203, in downloading
> aria2_bot  |     tasks = await client.tell_active()
> aria2_bot  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
> aria2_bot  |   File "/app/async_aria2_client.py", line 267, in tell_active
> aria2_bot  |     return data['result']
> aria2_bot  |            ~~~~^^^^^^^^^^
> aria2_bot  | KeyError: 'result'
> aria2      | 
> aria2      | 04/23 19:24:28 [NOTICE] Serialized session to '/config/aria2.session' successfully.
> aria2_bot  | rec message:{"jsonrpc":"2.0","method":"aria2.onDownloadStart","params":[{"gid":"875ebec621f5910b"}]}
> aria2_bot  | ===========下载 开始 任务id:875ebec621f5910b
> aria2      | 
> aria2      | 04/23 19:24:31 [NOTICE] Download complete: /downloads/__down
> aria2_bot  | 2024-04-23 19:24:31 debian-s-1vcpu-1gb-sfo3-01 asyncio[1] ERROR Task exception was never retrieved
> aria2_bot  | future: <Task finished name='Task-23' coro=<AsyncAria2Client.listen() done, defined at /app/async_aria2_client.py:42> exception=KeyError('result')>
> aria2_bot  | Traceback (most recent call last):
> aria2_bot  |   File "/app/async_aria2_client.py", line 55, in listen
> aria2_bot  |     await self.on_download_start(result)
> aria2_bot  |   File "/app/async_aria2_client.py", line 128, in on_download_start
> aria2_bot  |     tellStatus = await self.tell_status(gid)
> aria2_bot  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> aria2_bot  |   File "/app/async_aria2_client.py", line 110, in tell_status
> aria2_bot  |     return data['result']
> aria2_bot  |            ~~~~^^^^^^^^^^
> aria2_bot  | KeyError: 'result'
> aria2      | 04/23 19:24:31 [INFO] .aria2 file does not exist.
> aria2      | 04/23 19:24:31 [INFO] General download task, skipped delete .torrent file.
> aria2      | 04/23 19:24:31 [INFO] Deleting empty directory ...
> aria2      | 
> aria2      | 04/23 19:24:32 [NOTICE] Serialized session to '/config/aria2.session' successfully.
> ```
> 
> **docker compose**
> 
> ```
> version: "3.7"
> services:
>   aria2bot:
>     image: jwstar/aria2bot
>     network_mode: host
>     container_name: aria2_bot
>     restart: always
>     volumes:
>       - ./db:/app/db
>       - /root/docker/aria2-downloads:/downloads
>       - /qqqq:/qqqq
>     build: .
>     environment:
>       TZ: Asia/Shanghai
>   aria2:
>     image: p3terx/aria2-pro
>     container_name: aria2
>     restart: unless-stopped
>     ports:
>       - "6800:6800"
>       - "6888:6888"
>       - "6888:6888/udp"
>     environment:
>       - PUID=$UID
>       - PGID=$GID
>       - UMASK_SET=022
>       - RPC_SECRET=xxx
>       - RPC_PORT=6800
>       - LISTEN_PORT=6888
>     volumes:
>       - /root/docker/aria2-config:/config
>       - /root/docker/aria2-downloads:/downloads
>       - /qqqq:/qqqq
> ```

在另一台机器上正常启动了

---

另外请问一下能否增加一个自动上传aria2下载的文件至群组的功能，Bot的消息实在太多了，容易找不到文件，谢谢🙏

**Comment by jw-star** [comment]
https://github.com/jw-star/aria2bot/blob/805c12b07ea857650c124fb2d1c104dd30a99e99/db/config.example.yml#L4

设置这里为您的 频道或者群组id -100xxxx

**Comment by wanyunr** [comment]
> https://github.com/jw-star/aria2bot/blob/805c12b07ea857650c124fb2d1c104dd30a99e99/db/config.example.yml#L4
> 
> 设置这里为您的 频道或者群组id -100xxxx

设置 `ADMIN_ID`为群组后，键盘回复没有响应，docker 也没有相关报错日志，私聊也没有响应（Bot 也给了群组管理员）

![Clip_2024-04-25_01-39-49](https://github.com/jw-star/aria2bot/assets/105478325/cec3a282-cdc6-47b6-a67d-891a8fea56f0)

---
使用频道确实成功了，但是还是和 Bot私聊一样，会有非常的回复消息

可能是我没表达清楚，我希望是和`TG_FileStream`一样把上传了的文件再自动**转发**到一个频道和群组中，达到如下效果，谢谢🙏

![Clip_2024-04-25_01-54-19](https://github.com/jw-star/aria2bot/assets/105478325/242d600a-cc8b-4144-a9c3-11cf0fcfafd4)

**Comment by jw-star** [comment]
已增加转发id
