### ISSUE TITLE
能否支持 telegram 转载的图片和视频 ？

### ISSUE THREAD

**Issue by jerryc127** [jw-star/aria2bot#2]
能否支持 telegram 转载的图片和视频 ？

**Comment by jw-star** [comment]
我看下，能获取到直链就行，可以的话我加上

**Comment by jw-star** [comment]
为什么不直接下载到本地呢，其实不需要再添加到aria2 , 加到aria2,可能下载会快点其实

https://binbla.com/?p=339

这是一个下载的方式

**Comment by jerryc127** [comment]
因为这样就可以 一个 bot 就可以搞定一切，然后上传到网盘
加上 bot 方式也可以下载最新的所需的文件，你提供的那个链接的方法每次都要把整个群组都下载一遍

**Comment by jw-star** [comment]
是单独下载的

![image](https://user-images.githubusercontent.com/48782751/201484595-ec15a8fa-d410-48c0-9717-9d235a55b598.png)
